import { EventItem, UserSetup } from './types';

export const DEFAULT_USER: UserSetup = {
  city: 'Austin, TX',
  interests: ['Music', 'Nightlife'],
};

export const AVAILABLE_INTERESTS = ['Music', 'Arts', 'Nightlife', 'Campus', 'Comedy'];

export const EXPLORE_FILTERS = ['Tonight', 'This Weekend', 'Free', 'Live Music', '21+'];

export const AUSTIN_EVENTS: EventItem[] = [
  {
    id: 'evt_1',
    title: 'Neon Jungle Night',
    promoter: 'Electric Ave Productions',
    dateLabel: 'Fri, Oct 20',
    timeLabel: '9:00 PM - 3:00 AM',
    venue: 'Empire Control Room',
    address: '606 E 7th St',
    neighborhood: 'Red River',
    distanceMiles: 2.1,
    priceLabel: '$25 + fees',
    category: 'Club Night',
    ageRating: '21+',
    tags: ['Tonight', 'Live Music', '21+'],
    description:
      'An underground electronic showcase with local DJs, immersive lighting, and a late-night crowd from across Austin.',
    ticketUrl: 'https://example.com/tickets/neon-jungle',
    heroColor: '#0f5a57',
    friendInterested: 8,
    friendGoing: 3,
  },
  {
    id: 'evt_2',
    title: 'South Congress Art Walk',
    promoter: 'ATX Makers Guild',
    dateLabel: 'Sat, Oct 21',
    timeLabel: '5:30 PM - 9:30 PM',
    venue: 'South Congress Blocks',
    address: 'South Congress Ave',
    neighborhood: 'SoCo',
    distanceMiles: 4.8,
    priceLabel: 'Free',
    category: 'Arts',
    ageRating: 'All Ages',
    tags: ['This Weekend', 'Free', 'Arts'],
    description:
      'Studios, galleries, and pop-up vendors open late for a neighborhood-wide art night and community hangout.',
    ticketUrl: 'https://example.com/tickets/soco-art-walk',
    heroColor: '#7e3a13',
    friendInterested: 5,
    friendGoing: 1,
  },
  {
    id: 'evt_3',
    title: 'UT Rooftop DJ Session',
    promoter: 'Campus Nights',
    dateLabel: 'Thu, Oct 19',
    timeLabel: '8:00 PM - 12:00 AM',
    venue: 'Skyline Hall',
    address: '24th & Speedway',
    neighborhood: 'UT Area',
    distanceMiles: 1.4,
    priceLabel: '$10',
    category: 'Campus',
    ageRating: '18+',
    tags: ['Tonight', 'Campus', 'Live Music'],
    description:
      'Student-led rooftop session featuring house and afrobeat sets with skyline views and quick-entry RSVP.',
    ticketUrl: 'https://example.com/tickets/ut-rooftop',
    heroColor: '#2a3f8a',
    friendInterested: 11,
    friendGoing: 4,
  },
  {
    id: 'evt_4',
    title: 'East Austin Comedy Block',
    promoter: 'Laugh Circuit',
    dateLabel: 'Sun, Oct 22',
    timeLabel: '7:00 PM - 10:30 PM',
    venue: 'The Brass Room',
    address: '1204 E 11th St',
    neighborhood: 'East Austin',
    distanceMiles: 2.6,
    priceLabel: '$15',
    category: 'Comedy',
    ageRating: '18+',
    tags: ['This Weekend', 'Comedy'],
    description:
      'Three rotating stand-up lineups in one venue with neighborhood food pop-ups and after-show networking.',
    ticketUrl: 'https://example.com/tickets/east-austin-comedy',
    heroColor: '#6a2b4f',
    friendInterested: 2,
    friendGoing: 1,
  },
  {
    id: 'evt_5',
    title: 'Sunset House on the Lake',
    promoter: 'Lakefront Series',
    dateLabel: 'Sat, Oct 21',
    timeLabel: '6:00 PM - 11:00 PM',
    venue: 'Laguna Deck',
    address: '2200 Lake Austin Blvd',
    neighborhood: 'Tarrytown',
    distanceMiles: 6.2,
    priceLabel: '$30',
    category: 'Nightlife',
    ageRating: '21+',
    tags: ['This Weekend', 'Live Music', '21+'],
    description:
      'Open-air sunset set by touring and local house artists with limited-entry capacity and lakeside visuals.',
    ticketUrl: 'https://example.com/tickets/sunset-house',
    heroColor: '#3d5a80',
    friendInterested: 7,
    friendGoing: 2,
  },
  {
    id: 'evt_6',
    title: 'Community Jazz Jam',
    promoter: 'Third Place Sessions',
    dateLabel: 'Wed, Oct 18',
    timeLabel: '7:30 PM - 10:00 PM',
    venue: 'North Loop Social Hall',
    address: '5601 N Lamar Blvd',
    neighborhood: 'North Loop',
    distanceMiles: 5.4,
    priceLabel: 'Free',
    category: 'Music',
    ageRating: 'All Ages',
    tags: ['Tonight', 'Free', 'Live Music'],
    description:
      'A low-pressure local jam night featuring rotating musicians and open sign-up slots for instrumentalists.',
    ticketUrl: 'https://example.com/tickets/jazz-jam',
    heroColor: '#0f5749',
    friendInterested: 4,
    friendGoing: 0,
  },
];
