import { EventItem, UserSetup } from './types';

export const DEFAULT_USER: UserSetup = {
  city: 'Austin, TX',
  interests: ['DIY', 'Film'],
};

export const AVAILABLE_INTERESTS = [
  'DIY',
  'Film',
  'Zines',
  'Community',
  'Nightlife',
  'Comedy',
];

export const EXPLORE_FILTERS = ['Tonight', 'This Weekend', 'Free', 'All Ages', 'DIY'];

export const AUSTIN_EVENTS: EventItem[] = [
  {
    id: 'evt_1',
    title: 'Warehouse Print + Zine Night',
    promoter: 'Paper Cuts Collective',
    dateLabel: 'Fri, Oct 20',
    timeLabel: '7:00 PM - 11:30 PM',
    venue: 'The Mourning Doves Studio',
    address: '1512 E Cesar Chavez St',
    neighborhood: 'East Cesar Chavez',
    distanceMiles: 2.3,
    priceLabel: '$8',
    category: 'DIY',
    ageRating: 'All Ages',
    tags: ['Tonight', 'DIY', 'All Ages'],
    description:
      'A late printmaking session with mini zine tables, open collage wall, and low-key ambient sets between workshops.',
    ticketUrl: 'https://example.com/tickets/warehouse-zine-night',
    heroColor: '#3a1b53',
    friendInterested: 9,
    friendGoing: 4,
  },
  {
    id: 'evt_2',
    title: 'Rooftop Silent Film + Live Score',
    promoter: 'Moonlight Reels',
    dateLabel: 'Sat, Oct 21',
    timeLabel: '8:30 PM - 11:00 PM',
    venue: 'Canopy Terrace',
    address: '916 Springdale Rd',
    neighborhood: 'Govalle',
    distanceMiles: 3.9,
    priceLabel: 'Free',
    category: 'Film',
    ageRating: 'All Ages',
    tags: ['This Weekend', 'Free', 'All Ages'],
    description:
      'A projected silent thriller scored by local synth duo, with blankets, thermos coffee, and a bring-your-own-chair setup.',
    ticketUrl: 'https://example.com/tickets/silent-film-live-score',
    heroColor: '#23324d',
    friendInterested: 6,
    friendGoing: 2,
  },
  {
    id: 'evt_3',
    title: 'Mutant Flea: Vintage + Patch Swap',
    promoter: 'Night Shift Market',
    dateLabel: 'Sun, Oct 22',
    timeLabel: '1:00 PM - 6:00 PM',
    venue: 'Riveter Yard',
    address: '1300 E 5th St',
    neighborhood: 'East Austin',
    distanceMiles: 2.0,
    priceLabel: '$10',
    category: 'Community',
    ageRating: '18+',
    tags: ['This Weekend', 'DIY', 'All Ages'],
    description:
      'Curated vintage racks, hand-sewn patch bar, and barter lane for clothes, records, and old cameras.',
    ticketUrl: 'https://example.com/tickets/mutant-flea',
    heroColor: '#5f2e2c',
    friendInterested: 12,
    friendGoing: 5,
  },
  {
    id: 'evt_4',
    title: 'Queer Micro-Theater Marathon',
    promoter: 'Tiny Stage Project',
    dateLabel: 'Thu, Oct 19',
    timeLabel: '7:30 PM - 10:45 PM',
    venue: 'Black Box B',
    address: '1906 E 12th St',
    neighborhood: 'Chestnut',
    distanceMiles: 2.7,
    priceLabel: '$18',
    category: 'Theater',
    ageRating: '16+',
    tags: ['Tonight', 'DIY'],
    description:
      'Five original 15-minute pieces in one night, rotating sets every 30 minutes with cast Q&A between rounds.',
    ticketUrl: 'https://example.com/tickets/micro-theater-marathon',
    heroColor: '#2d4b3d',
    friendInterested: 4,
    friendGoing: 2,
  },
  {
    id: 'evt_5',
    title: 'Open Deck Night: Afro-Latin + House',
    promoter: 'Loose Frequency',
    dateLabel: 'Sat, Oct 21',
    timeLabel: '10:00 PM - 2:30 AM',
    venue: 'Side Room 73',
    address: '505 Trinity St',
    neighborhood: 'Downtown',
    distanceMiles: 1.8,
    priceLabel: '$15',
    category: 'Nightlife',
    ageRating: '21+',
    tags: ['This Weekend', 'DIY', '21+'],
    description:
      'Underground dance floor with open deck slots, no VIP sections, and a community-coded dress-up theme each week.',
    ticketUrl: 'https://example.com/tickets/open-deck-night',
    heroColor: '#4b245c',
    friendInterested: 8,
    friendGoing: 2,
  },
  {
    id: 'evt_6',
    title: 'Parking Lot Poetry Slam',
    promoter: 'Loudmouth Commons',
    dateLabel: 'Wed, Oct 18',
    timeLabel: '8:00 PM - 10:30 PM',
    venue: 'Littlefield Lot',
    address: '1601 E 6th St',
    neighborhood: 'Holly',
    distanceMiles: 2.9,
    priceLabel: 'Free',
    category: 'Poetry',
    ageRating: 'All Ages',
    tags: ['Tonight', 'Free', 'All Ages'],
    description:
      'Street-style spoken word under string lights with 3-minute rounds, live vote cards, and free chai.',
    ticketUrl: 'https://example.com/tickets/parking-lot-poetry-slam',
    heroColor: '#214442',
    friendInterested: 7,
    friendGoing: 3,
  },
  {
    id: 'evt_7',
    title: 'No Laptop Jam Circle',
    promoter: 'Patch Cable Social',
    dateLabel: 'Mon, Oct 23',
    timeLabel: '6:30 PM - 9:30 PM',
    venue: 'Signal House',
    address: '2414 Webberville Rd',
    neighborhood: 'Govalle',
    distanceMiles: 3.4,
    priceLabel: '$5',
    category: 'Workshop',
    ageRating: 'All Ages',
    tags: ['This Weekend', 'DIY', 'All Ages'],
    description:
      'Bring hardware synths, samplers, or drum machines for a no-laptop jam session and skill-share mini demos.',
    ticketUrl: 'https://example.com/tickets/no-laptop-jam-circle',
    heroColor: '#3c3f66',
    friendInterested: 5,
    friendGoing: 1,
  },
  {
    id: 'evt_8',
    title: 'Mutual Aid Food Fair + Teach-In',
    promoter: 'East Side Care Network',
    dateLabel: 'Sun, Oct 22',
    timeLabel: '12:00 PM - 4:00 PM',
    venue: 'Parque Zaragoza',
    address: '2608 Gonzales St',
    neighborhood: 'Govalle',
    distanceMiles: 4.1,
    priceLabel: 'Free',
    category: 'Community',
    ageRating: 'All Ages',
    tags: ['This Weekend', 'Free', 'All Ages'],
    description:
      'Community cookout, local resource tables, and short teach-ins on tenant rights, first aid, and neighborhood organizing.',
    ticketUrl: 'https://example.com/tickets/mutual-aid-food-fair',
    heroColor: '#6b5130',
    friendInterested: 10,
    friendGoing: 4,
  },
];
