import { EventItem, EventKind, EventTasteQuestion, UserRole, UserSetup } from './types';

export const DEFAULT_USER: UserSetup = {
  id: '',
  email: '',
  profileName: '',
  profileImageUrl: '',
  city: 'Austin, TX',
  interests: ['DIY', 'Film'],
  role: 'event_enjoyer',
  tasteAnswers: {},
};

export const PROFILE_ROLES: { id: UserRole; title: string; description: string }[] = [
  {
    id: 'concert_lover',
    title: 'Concert Lover',
    description: 'Prioritize live sets, tours, and performance-heavy nights.',
  },
  {
    id: 'event_enjoyer',
    title: 'Event Enjoyer',
    description: 'Discover all kinds of local events across scenes and neighborhoods.',
  },
  {
    id: 'promoter',
    title: 'Promoter',
    description: 'Publish flyers, manage events, and track attendance intent.',
  },
];

export const AVAILABLE_INTERESTS = [
  'DIY',
  'Film',
  'Zines',
  'Community',
  'Nightlife',
  'Comedy',
];

export const EXPLORE_FILTERS = ['Tonight', 'This Weekend', 'Free', 'All Ages', 'DIY'];

export const EVENT_KIND_FILTERS: { id: 'all' | EventKind; label: string }[] = [
  { id: 'all', label: 'All Kinds' },
  { id: 'concert', label: 'Concerts' },
  { id: 'film', label: 'Film' },
  { id: 'meetup', label: 'Meetups' },
  { id: 'comedy', label: 'Comedy' },
  { id: 'arts', label: 'Arts/Theater' },
];

export const EVENT_SUBCATEGORIES_BY_KIND: Record<EventKind, string[]> = {
  concert: ['Punk', 'Metal', 'Rock', 'Pop', 'House', 'Electronic', 'Jazz'],
  film: ['Arthouse', 'Horror', 'Documentary', 'Experimental'],
  meetup: ['Community', 'Poetry', 'Mutual Aid', 'Workshops', 'Markets'],
  comedy: ['Stand-up', 'Improv', 'Alt Comedy'],
  arts: ['Zine/Print', 'Theater', 'Gallery', 'Performance Art'],
};

export const LOGIN_QUESTIONS: EventTasteQuestion[] = [
  {
    id: 'event_type',
    prompt: 'Which scenes pull you in first?',
    options: ['Punk concerts', 'Arthouse screenings', 'Community meetups', 'DIY art nights'],
  },
  {
    id: 'concert_subgenre',
    prompt: 'Pick a concert lane you would follow.',
    options: ['Metal gigs', 'Rock shows', 'Pop concerts', 'House DJ sets'],
  },
  {
    id: 'non_music_pick',
    prompt: 'Which non-music event sounds best tonight?',
    options: ['Poetry circles', 'Indie film nights', 'Zine fairs', 'Comedy shows'],
  },
  {
    id: 'weekend_daytime',
    prompt: 'What daytime weekend plan fits you most?',
    options: ['Flea markets', 'Gallery pop-ups', 'Mutual aid events', 'Workshops'],
  },
  {
    id: 'budget_style',
    prompt: 'What ticket style works for you?',
    options: ['Free community events', 'Under $20 shows', 'Special $20-$40 nights', 'Mix of everything'],
  },
];

export const AUSTIN_EVENTS: EventItem[] = [
  {
    id: 'evt_1',
    title: 'Warehouse Print + Zine Night',
    promoter: 'Paper Cuts Collective',
    postedByUserId: 'usr_paper_cuts',
    dateLabel: 'Fri, Oct 20',
    timeLabel: '7:00 PM - 11:30 PM',
    startAtIso: '2026-10-20T19:00:00-05:00',
    endAtIso: '2026-10-20T23:30:00-05:00',
    venue: 'The Mourning Doves Studio',
    address: '1512 E Cesar Chavez St',
    neighborhood: 'East Cesar Chavez',
    distanceMiles: 2.3,
    priceLabel: '$8',
    category: 'DIY',
    ageRating: 'All Ages',
    tags: ['Tonight', 'DIY', 'All Ages'],
    description:
      'A late printmaking session with mini zine tables, open collage wall, and low-key ambient sets between workshops.',
    ticketUrl: 'https://example.com/tickets/warehouse-zine-night',
    flyerImageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/2/2c/1st_Woodcuts_Exhibition_of_%22Ryt%22_Association.jpg',
    heroColor: '#3a1b53',
    latitude: 30.2576,
    longitude: -97.7177,
    kind: 'arts',
    subcategory: 'Zine/Print',
    friendInterested: 9,
    friendGoing: 4,
    postedByRole: 'event_enjoyer',
    moderationStatus: 'accepted',
  },
  {
    id: 'evt_2',
    title: 'Rooftop Silent Film + Live Score',
    promoter: 'Moonlight Reels',
    postedByUserId: 'usr_moonlight_reels',
    dateLabel: 'Sat, Oct 21',
    timeLabel: '8:30 PM - 11:00 PM',
    startAtIso: '2026-10-21T20:30:00-05:00',
    endAtIso: '2026-10-21T23:00:00-05:00',
    venue: 'Canopy Terrace',
    address: '916 Springdale Rd',
    neighborhood: 'Govalle',
    distanceMiles: 3.9,
    priceLabel: 'Free',
    category: 'Film',
    ageRating: 'All Ages',
    tags: ['This Weekend', 'Free', 'All Ages'],
    description:
      'A projected silent thriller scored by local synth duo, with blankets, thermos coffee, and a bring-your-own-chair setup.',
    ticketUrl: 'https://example.com/tickets/silent-film-live-score',
    flyerImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/07/The_Cameraman_%28Keaton%29_poster.jpg',
    heroColor: '#23324d',
    latitude: 30.2624,
    longitude: -97.7024,
    kind: 'film',
    subcategory: 'Arthouse',
    friendInterested: 6,
    friendGoing: 2,
    postedByRole: 'promoter',
    moderationStatus: 'accepted',
  },
  {
    id: 'evt_3',
    title: 'Mutant Flea: Vintage + Patch Swap',
    promoter: 'Night Shift Market',
    postedByUserId: 'usr_night_shift_market',
    dateLabel: 'Sun, Oct 22',
    timeLabel: '1:00 PM - 6:00 PM',
    startAtIso: '2026-10-22T13:00:00-05:00',
    endAtIso: '2026-10-22T18:00:00-05:00',
    venue: 'Riveter Yard',
    address: '1300 E 5th St',
    neighborhood: 'East Austin',
    distanceMiles: 2.0,
    priceLabel: '$10',
    category: 'Community',
    ageRating: '18+',
    tags: ['This Weekend', 'DIY', 'All Ages'],
    description:
      'Curated vintage racks, hand-sewn patch bar, and barter lane for clothes, records, and old cameras.',
    ticketUrl: 'https://example.com/tickets/mutant-flea',
    flyerImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/47/Affiche_Foire_2013_%2814468465820%29.jpg',
    heroColor: '#5f2e2c',
    latitude: 30.2632,
    longitude: -97.7285,
    kind: 'meetup',
    subcategory: 'Markets',
    friendInterested: 12,
    friendGoing: 5,
    postedByRole: 'promoter',
    moderationStatus: 'accepted',
  },
  {
    id: 'evt_4',
    title: 'Queer Micro-Theater Marathon',
    promoter: 'Tiny Stage Project',
    postedByUserId: 'usr_tiny_stage',
    dateLabel: 'Thu, Oct 19',
    timeLabel: '7:30 PM - 10:45 PM',
    startAtIso: '2026-10-19T19:30:00-05:00',
    endAtIso: '2026-10-19T22:45:00-05:00',
    venue: 'Black Box B',
    address: '1906 E 12th St',
    neighborhood: 'Chestnut',
    distanceMiles: 2.7,
    priceLabel: '$18',
    category: 'Theater',
    ageRating: '16+',
    tags: ['Tonight', 'DIY'],
    description:
      'Five original 15-minute pieces in one night, rotating sets every 30 minutes with cast Q&A between rounds.',
    ticketUrl: 'https://example.com/tickets/micro-theater-marathon',
    flyerImageUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/7f/Ionesco-affiche.jpg',
    heroColor: '#2d4b3d',
    latitude: 30.2741,
    longitude: -97.7188,
    kind: 'arts',
    subcategory: 'Theater',
    friendInterested: 4,
    friendGoing: 2,
    postedByRole: 'event_enjoyer',
    moderationStatus: 'accepted',
  },
  {
    id: 'evt_5',
    title: 'Open Deck Night: Afro-Latin + House',
    promoter: 'Loose Frequency',
    postedByUserId: 'usr_loose_frequency',
    dateLabel: 'Sat, Oct 21',
    timeLabel: '10:00 PM - 2:30 AM',
    startAtIso: '2026-10-21T22:00:00-05:00',
    endAtIso: '2026-10-22T02:30:00-05:00',
    venue: 'Side Room 73',
    address: '505 Trinity St',
    neighborhood: 'Downtown',
    distanceMiles: 1.8,
    priceLabel: '$15',
    category: 'Nightlife',
    ageRating: '21+',
    tags: ['This Weekend', 'DIY', '21+'],
    description:
      'Underground dance floor with open deck slots, no VIP sections, and a community-coded dress-up theme each week.',
    ticketUrl: 'https://example.com/tickets/open-deck-night',
    flyerImageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/9/9b/Mixmag_%26_DSI_Tour_2010_with_Jack_Beats_and_Surkin.jpg',
    heroColor: '#4b245c',
    latitude: 30.2665,
    longitude: -97.7394,
    kind: 'concert',
    subcategory: 'House',
    friendInterested: 8,
    friendGoing: 2,
    postedByRole: 'promoter',
    moderationStatus: 'accepted',
  },
  {
    id: 'evt_6',
    title: 'Parking Lot Poetry Slam',
    promoter: 'Loudmouth Commons',
    postedByUserId: 'usr_loudmouth_commons',
    dateLabel: 'Wed, Oct 18',
    timeLabel: '8:00 PM - 10:30 PM',
    startAtIso: '2026-10-18T20:00:00-05:00',
    endAtIso: '2026-10-18T22:30:00-05:00',
    venue: 'Littlefield Lot',
    address: '1601 E 6th St',
    neighborhood: 'Holly',
    distanceMiles: 2.9,
    priceLabel: 'Free',
    category: 'Poetry',
    ageRating: 'All Ages',
    tags: ['Tonight', 'Free', 'All Ages'],
    description:
      'Street-style spoken word under string lights with 3-minute rounds, live vote cards, and free chai.',
    ticketUrl: 'https://example.com/tickets/parking-lot-poetry-slam',
    flyerImageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/7/7e/John_Ashbery_%28MCA_poetry_reading_poster%2C_1977%29.jpg',
    heroColor: '#214442',
    latitude: 30.257,
    longitude: -97.7212,
    kind: 'meetup',
    subcategory: 'Poetry',
    friendInterested: 7,
    friendGoing: 3,
    postedByRole: 'concert_lover',
    moderationStatus: 'accepted',
  },
  {
    id: 'evt_7',
    title: 'No Laptop Jam Circle',
    promoter: 'Patch Cable Social',
    postedByUserId: 'usr_patch_cable_social',
    dateLabel: 'Mon, Oct 23',
    timeLabel: '6:30 PM - 9:30 PM',
    startAtIso: '2026-10-23T18:30:00-05:00',
    endAtIso: '2026-10-23T21:30:00-05:00',
    venue: 'Signal House',
    address: '2414 Webberville Rd',
    neighborhood: 'Govalle',
    distanceMiles: 3.4,
    priceLabel: '$5',
    category: 'Workshop',
    ageRating: 'All Ages',
    tags: ['This Weekend', 'DIY', 'All Ages'],
    description:
      'Bring hardware synths, samplers, or drum machines for a no-laptop jam session and skill-share mini demos.',
    ticketUrl: 'https://example.com/tickets/no-laptop-jam-circle',
    flyerImageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/0/01/Tokyo_Festival_of_Modular_2016_-_6.10_Friday_Premium_Live_of_Modular_-_program_%282016-06-10_by_Kazuhisa_OTSUBO%29.jpg',
    heroColor: '#3c3f66',
    latitude: 30.2501,
    longitude: -97.7089,
    kind: 'concert',
    subcategory: 'Electronic',
    friendInterested: 5,
    friendGoing: 1,
    postedByRole: 'event_enjoyer',
    moderationStatus: 'accepted',
  },
  {
    id: 'evt_8',
    title: 'Mutual Aid Food Fair + Teach-In',
    promoter: 'East Side Care Network',
    postedByUserId: 'usr_east_side_care',
    dateLabel: 'Sun, Oct 22',
    timeLabel: '12:00 PM - 4:00 PM',
    startAtIso: '2026-10-22T12:00:00-05:00',
    endAtIso: '2026-10-22T16:00:00-05:00',
    venue: 'Parque Zaragoza',
    address: '2608 Gonzales St',
    neighborhood: 'Govalle',
    distanceMiles: 4.1,
    priceLabel: 'Free',
    category: 'Community',
    ageRating: 'All Ages',
    tags: ['This Weekend', 'Free', 'All Ages'],
    description:
      'Community cookout, local resource tables, and short teach-ins on tenant rights, first aid, and neighborhood organizing.',
    ticketUrl: 'https://example.com/tickets/mutual-aid-food-fair',
    flyerImageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/e/e3/Affiche_Foire_%C3%A0_l%27autogestion_%2820883091581%29.jpg',
    heroColor: '#6b5130',
    latitude: 30.2637,
    longitude: -97.7001,
    kind: 'meetup',
    subcategory: 'Mutual Aid',
    friendInterested: 10,
    friendGoing: 4,
    postedByRole: 'promoter',
    moderationStatus: 'accepted',
  },
];
